[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Balloon Model"
authors = [{name = "Rodrigo", email = "rodrigo.avaria@uv.cl"}]
dynamic = ["version", "description"]
